### ISSUE TITLE
Implement a `translate` transformation function

### ISSUE THREAD

**Issue by Sudha247** [Sudha247/ocaml-joy#12]
`translate x y shape`  returns a new shape that's moved by `x` on the x-axis and `y` on the y-axis. For instance, `translate 100 100 (circle 50)` would return a new circle that has its centre at the co-ordinates (100, 100).

The type signature of the function would be:

```ocaml
translate : int -> int -> shape -> shape
```

**Comment by nangahamandine** [comment]
Hello, can I please be assigned to this issue?

**Comment by nangahamandine** [comment]
> `translate x y shape` returns a new shape that's moved by `x` on the x-axis and `y` on the y-axis. For instance, `translate 100 100 (circle 50)` would return a new circle that has its centre at the co-ordinates (100, 100).
> 
> The type signature of the function would be:
> 
> ```ocaml
> translate : int -> int -> shape -> shape
> ```

Can you please elaborate on how we are supposed to contribute to this issue?
I understand the translated but I'm not sure what is required.

**Comment by Sudha247** [comment]
> Do I need to implement functions to translate the various shapes?

Yes. It should work for `circle`, `rectangle` and `ellipse`.

> Also, I'd like an example on one of the shapes so it'll guide me with doing the others.

Sure, imagine we're creating a rectangle of `length = 200` and `width = 100`. That looks something like

```ocaml
let r1 = rectangle 200 100 in
```

Now, imagine I want to move the rectangle 100 units right of origin on the x-axis. I should be able to use the translate function as follows

```ocaml
let r2 = translate 100 0 r1 in
show [r1; r2] (*displays both rectangles*)
```

**Comment by nangahamandine** [comment]
Okay, thank you for elaborating.
Just to make sure, I'll implement these translations inside the shape's files in the `example` directory right?

**Comment by Sudha247** [comment]
No, the implementation has to be in shape.ml in the `lib/` directory: https://github.com/Sudha247/ocaml-joy/blob/main/lib/shape.ml

**Comment by nangahamandine** [comment]
Okay, awesome! I get it now :)

**Comment by nangahamandine** [comment]
I have a question. How do I test the implementation to be sure that I've done it right before committing?

**Comment by Sudha247** [comment]
You don't need to call the compiler directly. You can do `dune build` within the `ocaml-joy` directory to build the project. I'd recommend adding a simple test like create a circle, translate it, and then display.

**Comment by nangahamandine** [comment]
Okay, thank you for this
I've done that but I don't get a display yet

**Comment by nikochiko** [comment]
@nangahamandine what do the terminal's logs say?

If there was no error in the logs, can you try checking other windows in case the display opened silently?

**Comment by nikochiko** [comment]
Ah, I see that the display opened for you for some other issues.
Great! It is intentional now that you don't see the display. You can go about testing your changes by adding to examples and using the new function. I'll be able to help better with that if you can share your changes in a pull request.

**Comment by nangahamandine** [comment]
Okay, thank you. So do I just commit the changes and open a PR without?

**Comment by nikochiko** [comment]
Completed with #20
