### ISSUE TITLE
Potential features and examples

### ISSUE THREAD

**Issue by FayCarsons** [Sudha247/ocaml-joy#15]
I noticed in the initial outreachy issue that you were open to suggestions so I thought I'd share some ideas I have :) 

- Rotation function
- circle packing example, to demonstrate more complex usage of the library 
- N-sided polygon 
- SDF based geometries (haven't dug deeply into the implementation so unsure if this is possible, but would allow for smooth unions, intersections, domain repetition, etc)

I could definitely come up with more! 

Would be happy to take on any/all of these, this is sort of my area of expertise, let me know :)

**Comment by nikochiko** [comment]
@FayCarsons awesome! Your ideas are very interesting. I learnt about circle packing and sdf from this issue.

We do plan to have support for rotation and N-sided polygons. The documentation of the original Python library called Joy can be found here -- https://github.com/fossunited/joy/blob/main/README.md, and there is more at https://github.com/fossunited/joy/blob/d8f062a057df3f3ef9445032e7e09674d0c418fc/tutorial.ipynb

The first priority at the moment is to achieve parity with this, and make something composable that is
- simple enough that a new learner can ease into it
- powerful enough to achieve all of these use cases

Are you participating in the outreachy program?

**Comment by FayCarsons** [comment]
Hi! I am an outreachy participant :) 

I can absolutely prioritize more simple features present in the python lib, which I'll take a deeper look at. Maybe rotation would be a good place to start?

**Comment by nikochiko** [comment]
Please start with #13 for now. We can move to rotation after that, as a medium-size issue rather than a small good-first-issue.

**Comment by FayCarsons** [comment]
Just submitted a PR for #13, a couple other small ideas I have: A Line type with render function etc, and a function for converting a 2-tuple into a dimensions string for setting the dimensions of the window. I think now that I'm getting the hang of OCaml I could knock both of these out today.

**Comment by FayCarsons** [comment]
Another thought I had: the large majority of the examples are currently not using the library, but are instead using the graphics library and copies or near-copies of this library's functions which seems repetitive and confusing to me. I would be happy to go through and refactor them all so that they actually use Joy.

**Comment by nangahamandine** [comment]
> I noticed in the initial outreachy issue that you were open to suggestions so I thought I'd share some ideas I have :)
> 
>     * Rotation function
> 
>     * circle packing example, to demonstrate more complex usage of the library
> 
>     * N-sided polygon
> 
>     * SDF based geometries (haven't dug deeply into the implementation so unsure if this is possible, but would allow for smooth unions, intersections, domain repetition, etc)
> 
> 
> I could definitely come up with more!
> 
> Would be happy to take on any/all of these, this is sort of my area of expertise, let me know :)

Wow! These are some amazing suggestions!
I'd love to collab with you to realize these changes if that's okay.

**Comment by nangahamandine** [comment]
> Another thought I had: the large majority of the examples are currently not using the library, but are instead using the graphics library and copies or near-copies of this library's functions which seems repetitive and confusing to me. I would be happy to go through and refactor them all so that they actually use Joy.

But I thought the graphics library is an OCaml library whereas Joy is what we're referencing. I probably didn't properly understand properly from reading through the documentations. Please correct me if I'm wrong.
