### ISSUE TITLE
Graphics example: traffic signal

### ISSUE THREAD

**Issue by Sudha247** [Sudha247/ocaml-joy#18]
We use `graphics` library for joy's implementation. It'd be useful to understand how graphics works. This is a suggestion for creating an illustration with the graphics library.

Make a traffic light illustration that's a combination of a black reactangle, and red, amber and green circles placed at equal widths. Please try to add a screenshot of your result with the PR.

Note: This is meant as a first issue. If you've already worked on a `good-first-issue` and opened a PR, please look for issues tagged `help-wanted`.

**Comment by khushishikhu** [comment]
Hi @Sudha247  I am an outreachy applicant for december cohort. I am interested in working with this issue, please assign it to me

**Comment by Sudha247** [comment]
Hi @khushishikhu, thanks for your interest. Have you been able to setup OCaml on your machine and build this project?

**Comment by TitilayoAdeyemi** [comment]
Hi @Sudha247 Is this issue still available? I'd like to work on it if it is still available

**Comment by nangahamandine** [comment]
> We use `graphics` library for joy's implementation. It'd be useful to understand how graphics works. This is a suggestion for creating an illustration with the graphics library.
> 
> Make a traffic light illustration that's a combination of a black reactangle, and red, amber and green circles placed at equal widths. Please try to add a screenshot of your result with the PR.
> 
> Note: This is meant as a first issue. If you've already worked on a `good-first-issue` and opened a PR, please look for issues tagged `help-wanted`.

Awesome! This sounds exciting!
I'd love t work on this if that's okay.

**Comment by Raven49** [comment]
Hi @Sudha247 , I am an outreachy applicant and I would like to work on this issue .

**Comment by nikochiko** [comment]
@Raven49 go ahead!

**Comment by nikochiko** [comment]
@Raven49 are you still working on this?

**Comment by Sudha247** [comment]
Closing this as we're not actively developing the graphics backend and have switched to Cairo backend.
