### ISSUE TITLE
Triangle Shape implementation in Joy Library

### ISSUE THREAD

**Issue by kushalpokharel** [Sudha247/ocaml-joy#22]
### Description
As of now, the Joy Library doesn't support drawing `triangles`. However, there is already an existing example of drawing a triangle. 
- A Triangle constructor would be added to the Shape type
- The function to draw a triangle would accept three parameters of type Point. 
- The lines are drawn from the first point to the second, second to the third, and third to the first to make a triangle. 

### Future improvements
- We could also add a function that draws a triangle by accepting two Points (A and B) an angle parameter (ABC) and the length of the side (BC) to draw the triangle

**Comment by joanita-51** [comment]
Hi @kushalpokharel , are you looking for someone to work on this issue?

**Comment by Mankavelda** [comment]
> ### Description
> As of now, the Joy Library doesn't support drawing `triangles`. However, there is already an existing example of drawing a triangle.
> 
> * A Triangle constructor would be added to the Shape type
> * The function to draw a triangle would accept three parameters of type Point.
> * The lines are drawn from the first point to the second, second to the third, and third to the first to make a triangle.
> 
> ### Future improvements
> * We could also add a function that draws a triangle by accepting two Points (A and B) an angle parameter (ABC) and the length of the side (BC) to draw the triangle

Hello @kushalpokharel I can work on this issue

**Comment by TitilayoAdeyemi** [comment]
Hi @Mankavelda Please I need help with setting up the ocaml-joy project on my system. I have been facing different errors and have not been able to contribute since. I'd really like for you to put me through on the steps to take. Thank you!

**Comment by joanita-51** [comment]
@TitilayoAdeyemi , what operating system are you using?

**Comment by TitilayoAdeyemi** [comment]
> @TitilayoAdeyemi , what operating system are you using?

Hi @joanita-51 I am using a Windows operating system

**Comment by Sudha247** [comment]
Thanks for creating the issue. I discussed this offline with @nikochiko and we're not sure triangle is a good abstraction for `joy`. `joy` aims to have a really simple user facing API, and I'm not fully convinced a triangle would fit in well. However, a n-sided polygon with reasonable defaults might be a good addition. But, let's reserve that for later.

**Comment by Mankavelda** [comment]
> Hi @Mankavelda Please I need help with setting up the ocaml-joy project on my system. I have been facing different errors and have not been able to contribute since. I'd really like for you to put me through on the steps to take. Thank you!

Hello @TitilayoAdeyemi , did you follow this #1 ?

**Comment by kushalpokharel** [comment]
Hi @Sudha247 , thank you for your feedback. We could discuss the n-sided polygon and how defaults will be chosen.  I need to work on something. Please assign me a task

**Comment by joanita-51** [comment]
> > @TitilayoAdeyemi , what operating system are you using?
> 
> Hi @joanita-51 I am using a Windows operating system

I think @nangahamandine would be more helpful, as she is using Windows. I'm using Ubuntu and followed the steps outlined in #1. You can also check #5 for details, where someone discussed the use of WSL for Windows users. and also look at #3  for the steps outlined by [@AryanGodara ](https://github.com/Sudha247/ocaml-joy/issues/3#issuecomment-1744606554)

**Comment by nangahamandine** [comment]
> > > @TitilayoAdeyemi , what operating system are you using?
> > 
> > 
> > Hi @joanita-51 I am using a Windows operating system
> 
> I think @nangahamandine would be more helpful, as she is using Windows. I'm using Ubuntu and followed the steps outlined in #1. You can also check #5 for details, where someone discussed the use of WSL for Windows users. and also look at #3 for the steps outlined by [@AryanGodara ](https://github.com/Sudha247/ocaml-joy/issues/3#issuecomment-1744606554)

Thanks for the suggestion @joanita-51. I've provided the suggestions that I could so far with installing the libraries on WSL, connecting WSL on VS Code and opening the project directory. Hopefully @TitilayoAdeyemi sorts it out after going through all the suggestions you've made.
Please get back to us if you still face issues after. If we can't help much then the mentors will certainly step in.

**Comment by TitilayoAdeyemi** [comment]
Thank you so much @joanita-51 
@nangahamandine Thank you so much too! I tried it out but it didn't work. I will delete and start over again, I'd give you feedback when I'm done with that. I am really grateful.

**Comment by nangahamandine** [comment]
> Thank you so much @joanita-51 @nangahamandine Thank you so much too! I tried it out but it didn't work. I will delete and start over again, I'd give you feedback when I'm done with that. I am really grateful.

You're welcome. I'm keeping my fingers crossed, hoping everything works. Will be here in case you have any further questions :)

**Comment by Sudha247** [comment]
@kushalpokharel I've created some new issues. Please feel free to take a look at them and pick up something.
