### ISSUE TITLE
Graphics Example: regular polygons

### ISSUE THREAD

**Issue by nikochiko** [Sudha247/ocaml-joy#26]
We use graphics library for joy's implementation. It'd be useful to understand how graphics works. This is a suggestion for creating an illustration with the graphics library.

Make regular polygons -- triangle, square, pentagon, hexagon -- in the same canvas. Use a canvas size of 500 x 500. 

Reference: https://ocaml.github.io/graphics/graphics/Graphics/index.html#val-draw_poly

**Comment by nikochiko** [comment]
@joanita-51 would you like to take this up?

**Comment by joanita-51** [comment]
Yes, i would love to

**Comment by nikochiko** [comment]
Please go ahead!

**Comment by nikochiko** [comment]
@joanita-51 were you able to make the local setup (as described in #1) and get the project to compile (`dune build`) ?

**Comment by joanita-51** [comment]
Y

> @joanita-51 were you able to make the local setup (as described in #1) and get the project to compile (`dune build`) ?

Yes, i was able to

**Comment by joanita-51** [comment]
Hey @nikochiko, we already have an implementation for the triangle polygon. Should I create another polygon using the draw_poly function?
