### ISSUE TITLE
Joy Example: A row of circles

### ISSUE THREAD

**Issue by Sudha247** [Sudha247/ocaml-joy#28]
With `Joy.Shape`, create a row of four circles equally spaced with the previous one. There's a similar example with plain graphics that needs to be ported to joy.

**Comment by kushalpokharel** [comment]
Hi @Sudha247 , I would like to work on this.

**Comment by Sudha247** [comment]
Sure, please go ahead.

**Comment by nikochiko** [comment]
Merged: https://github.com/Sudha247/ocaml-joy/pull/33
