### ISSUE TITLE
Basic illustrations with `graphics` library

### ISSUE THREAD

**Issue by Sudha247** [Sudha247/ocaml-joy#3]
Joy aims to provide a simple and approachable API for illustrating geometric shapes. Of course, one can do it directly with graphics library. The `examples` directory in this repo has an example that illustrates a circle. It'd be useful to have more examples in there, which we can later compare with the joy API. Here are some ideas for drawings --

* A simple rectangle
* Circle and a rectangle together
* Concentric circles
* Three circles in a row
* A grid of four circles just touching its adjacent ones
* *Feel free to come with something* 

Please mention below if you're working on any of these. Each of these examples can go into a separate ocaml source file within `examples`. When you're done with one of these, feel free to go ahead and make a PR to add it to `examples`.  You can refer to the `dune` file within the directory.

**Comment by nangahamandine** [comment]
I'd like to start working on this issue with first, the drawing of the simple rectangle. Just to make sure, this is the repo that I have to fork, create a branch and work on right? https://github.com/Sudha247/ocaml-joy

**Comment by Sudha247** [comment]
Yes, that's correct.

**Comment by nangahamandine** [comment]
How do I run the code to make sure that I can view my changes before making any commits? I just viewed the example `circle` and it's all red on my local machine. Making sure that I do it right
![Screenshot (206)](https://github.com/Sudha247/ocaml-joy/assets/78376414/fa9d1b93-bf27-4113-9a5f-2989a253ba6f)


Also, do I create the files in the `example` folder or in the `lib` folder?

**Comment by Sudha247** [comment]
This is the right directory.

You can run the examples with `dune`. Please install dune via opam before you proceed.

```
$ cd ocaml-joy
$ dune build examples/
$ dune exec -- examples/circle.exe
```

The above commands produce a graphics window with a circle.

**Comment by nangahamandine** [comment]
This is the result from the terminal

![Screenshot (207)](https://github.com/Sudha247/ocaml-joy/assets/78376414/2ccbf50a-2ec5-43b6-8ad5-26607a970784)

**Comment by nangahamandine** [comment]
I have dune 3.6.2 installed

**Comment by nangahamandine** [comment]
Also, I get this error after updating the /dune-project file from `(lang dune 3.10)` to `(lang dune 3.6)` and rerunning the command;

File "examples/dune", line 4, characters 12-20:
4 |  (libraries graphics))
                ^^^^^^^^
Error: Library "graphics" not found.
-> required by _build/default/examples/circle.exe
-> required by alias examples/all
-> required by alias examples/default


PS: I have dune 5.1.2 installed

**Comment by Mankavelda** [comment]
Hello, I have this error when running 
 dune exec -- examples/circle.exe
![Screenshot from 2023-10-03 08-18-39](https://github.com/Sudha247/ocaml-joy/assets/95079621/5e7cea63-8618-4d48-9467-f2b25f53d5ad)

**Comment by nangahamandine** [comment]
I have the same error. Did you successfully run the `dune build examples/` command?

**Comment by Mankavelda** [comment]
Oh I forgot to mention as @Sudha247 requested, I will love to work in this.
I see @nangahamandine is on it too, I hope both of us can work on same issue?

**Comment by Mankavelda** [comment]
> I have the same error. Did you successfully run the `dune build examples/` command?

No @nangahamandine , I didn't succeed

**Comment by AryanGodara** [comment]
@Mankavelda and @nangahamandine 
Did you use `opam install graphics` to install graphics dependency?

<br><br>
Also, first step on vscode should be to install the `ocaml-platform` extension. 

@nangahamandine you were getting all the rearedd lines because you haven't built your project beforehand, which is done using `dune build examples`
But since you're getting the dune version error.

Maybe checkout this [thread](https://discuss.ocaml.org/t/struggling-with-dune-and-opam-how-to-meet-dependencies-and-install-then-globally/12245/15) for a possible solution.

**Comment by AryanGodara** [comment]
> Oh I forgot to mention as @Sudha247 requested, I will love to work in this. I see @nangahamandine is on it too, I hope both of us can work on same issue?

We usually assign just one applicant to each issue.
But since everyone is having trouble setting up the repo, and we have multiple figures that one can draw, it's a good idea for both of you to open separate PRs for this one.

But first please coordinate which figure you want to draw, so that we don't get clashing PRs :)

**Comment by AryanGodara** [comment]
Can you share your opam versions here?
You need opam > 2.x.x

Then after setting up correct version of opam, run
```bash
opam update && opam upgrade
```

Then install the required version of dune using 
```bash
opam install "dune=x.y.z" // Keep this `3.0 to 3.9 range`
```
And then you can run the following command inside the examples directory
```bash
opam install graphics
```
This will install the relevant dependencies.

Then run
```bash
$ cd ocaml-joy // OR cd ..
$ dune build examples/
$ dune exec -- examples/circle.exe
```

**Comment by waringa-mercy** [comment]
@Sudha247 are there any other issues i can  attempt

**Comment by joanita-51** [comment]
@Sudha247 , i would love to contribute by drawing a sun

**Comment by Sudha247** [comment]
@nangahamandine 

> still no difference.

Do you mean dune still doesn't recognise that the graphics library is installed? It's quite odd. Anyways, I see that you're on a Windows machine. It's recommended to use WSL for running OCaml. You can perhaps try that.

@waringa-mercy - yes, you can go ahead with any of the unclaimed illustrations mentioned in this issue.

@joanita-51 - sure, that sounds great!

**Comment by nangahamandine** [comment]
> @nangahamandine
> 
> > still no difference.
> 
> Do you mean dune still doesn't recognise that the graphics library is installed? It's quite odd. Anyways, I see that you're on a Windows machine. It's recommended to use WSL for running OCaml. You can perhaps try that.
> 
> @waringa-mercy - yes, you can go ahead with any of the unclaimed illustrations mentioned in this issue.
> 
> @joanita-51 - sure, that sounds great!

Yes. Okay, I'm presently setting up wsl

**Comment by godplayer56** [comment]
> Can you share your opam versions here? You need opam > 2.x.x
> 
> Then after setting up correct version of opam, run
> 
> ```shell
> opam update && opam upgrade
> ```
> 
> Then install the required version of dune using
> 
> ```shell
> opam install "dune=x.y.z" // Keep this `3.0 to 3.9 range`
> ```
> 
> And then you can run the following command inside the examples directory
> 
> ```shell
> opam install graphics
> ```
> 
> This will install the relevant dependencies.
> 
> Then run
> 
> ```shell
> $ cd ocaml-joy // OR cd ..
> $ dune build examples/
> $ dune exec -- examples/circle.exe
> ```

Hello @AryanGodara, I was able to replicate these steps and my graphics library and dune build are working successfully and I can open run the exec commands for circle and circle graphs. :+1:

**Comment by AryanGodara** [comment]
> > Can you share your opam versions here? You need opam > 2.x.x
> > Then after setting up correct version of opam, run
> > ```shell
> > opam update && opam upgrade
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then install the required version of dune using
> > ```shell
> > opam install "dune=x.y.z" // Keep this `3.0 to 3.9 range`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And then you can run the following command inside the examples directory
> > ```shell
> > opam install graphics
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This will install the relevant dependencies.
> > Then run
> > ```shell
> > $ cd ocaml-joy // OR cd ..
> > $ dune build examples/
> > $ dune exec -- examples/circle.exe
> > ```
> 
> Hello @AryanGodara, I was able to replicate these steps and my graphics library and dune build are working successfully and I can open run the exec commands for circle and circle graphs. 👍

That's great @godplayer56
You can now start working on building your own examples from the above list if you have set up the Jupyter kernel

**Comment by FanyamTerkuma** [comment]
@Sudha247 and @AryanGodara , I am currently having issues with running OCaml code in vscode, OCaml platform extension has been installed along with the other dependencies but on running this command  "dune exec -- examples/circle.exe" the window displays without the circle. Please, how can I solve this? Here is a snapshot.
![Screenshot_20231003_131752](https://github.com/Sudha247/ocaml-joy/assets/89303855/fd5e2482-8894-4ef1-ba29-04851e052f34)

**Comment by AryanGodara** [comment]
> @Sudha247 and @AryanGodara , I am currently having issues with running OCaml code in vscode, OCaml platform extension has been installed along with the other dependencies but on running this command  "dune exec -- examples/circle.exe" the window displays without the circle. Please, how can I solve this? Here is a snapshot.
> 
> ![Screenshot_20231003_131752](https://github.com/Sudha247/ocaml-joy/assets/89303855/fd5e2482-8894-4ef1-ba29-04851e052f34)
> 
> 

Can you paste the steps you took after cloning the repo and the versions of your opam dependencies (dune graphics base server lap server etc) to get more idea

**Comment by FanyamTerkuma** [comment]
> > @Sudha247 and @AryanGodara , I am currently having issues with running OCaml code in vscode, OCaml platform extension has been installed along with the other dependencies but on running this command  "dune exec -- examples/circle.exe" the window displays without the circle. Please, how can I solve this? Here is a snapshot.
> > ![Screenshot_20231003_131752](https://user-images.githubusercontent.com/89303855/272257187-fd5e2482-8894-4ef1-ba29-04851e052f34.png)
> 
> Can you paste the steps you took after cloning the repo and the versions of your opam dependencies (dune graphics base server lap server etc) to get more idea
 
After cloning the repo, I created and switched to a new branch, then I navigated to the ocaml-joy directory and ran the following commands:
1. dune build examples/  ( after building the pfoject I then ran the following command)
2.  dune exec -- examples/circle.exe

Here are the versions of opam, dune, and graphics:
 opam version = 2.1.3
dune version =3.10.0
graphics version = 5.1.2

I don't know if this is enough information to help troubleshoot the problem

**Comment by AryanGodara** [comment]
Everyone using Windows. 
I suggest switching to WSL2. I tried to set up everything on Windows, and there were a lot of conflicts, especially when working with a diverse tech stack.

As for @FanyamTerkuma I'm not able to understand what the issue is in your case.
Is the same issue happening in circle_graph also?

**Comment by AryanGodara** [comment]
> > > @Sudha247 and @AryanGodara , I am currently having issues with running OCaml code in vscode, OCaml platform extension has been installed along with the other dependencies but on running this command  "dune exec -- examples/circle.exe" the window displays without the circle. Please, how can I solve this? Here is a snapshot.
> > > ![Screenshot_20231003_131752](https://user-images.githubusercontent.com/89303855/272257187-fd5e2482-8894-4ef1-ba29-04851e052f34.png)
> > 
> > 
> > Can you paste the steps you took after cloning the repo and the versions of your opam dependencies (dune graphics base server lap server etc) to get more idea
> 
> After cloning the repo, I created and switched to a new branch, then I navigated to the ocaml-joy directory and ran the following commands:
> 
> 1. dune build examples/  ( after building the pfoject I then ran the following command)
> 2. dune exec -- examples/circle.exe
> 
> Here are the versions of opam, dune, and graphics: opam version = 2.1.3 dune version =3.10.0 graphics version = 5.1.2
> 
> I don't know if this is enough information to help troubleshoot the problem

@FanyamTerkuma I think I understand your issue.
It may be regarding the dimensions of the background and the circle.
You see, in the circle.ml file, the three coordinates may be seen as x , y , radius
So, maybe the pixels are being drawn outside of the visible region of the background, or is too small to view for some reason.
Try to tweak around with the dimensions in the circle.ml file to see if this works

**Comment by nangahamandine** [comment]
Hello everyone! 
I already did the illustrations for a simple rectangle and concentric circles. I'm moving on to write code for the other shapes. 
Please let me know  if any of you is presently working on the other shapes. Otherwise, I'd like for this issue to be assigned to me exclusively so I can work on the other shapes and complete them in the next 24 hours

**Comment by FanyamTerkuma** [comment]
> > > > @Sudha247 and @AryanGodara , I am currently having issues with running OCaml code in vscode, OCaml platform extension has been installed along with the other dependencies but on running this command  "dune exec -- examples/circle.exe" the window displays without the circle. Please, how can I solve this? Here is a snapshot.
> > > > ![Screenshot_20231003_131752](https://user-images.githubusercontent.com/89303855/272257187-fd5e2482-8894-4ef1-ba29-04851e052f34.png)
> > > 
> > > 
> > > Can you paste the steps you took after cloning the repo and the versions of your opam dependencies (dune graphics base server lap server etc) to get more idea
> > 
> > 
> > After cloning the repo, I created and switched to a new branch, then I navigated to the ocaml-joy directory and ran the following commands:
> > 
> > 1. dune build examples/  ( after building the pfoject I then ran the following command)
> > 2. dune exec -- examples/circle.exe
> > 
> > Here are the versions of opam, dune, and graphics: opam version = 2.1.3 dune version =3.10.0 graphics version = 5.1.2
> > I don't know if this is enough information to help troubleshoot the problem
> 
> @FanyamTerkuma I think I understand your issue. It may be regarding the dimensions of the background and the circle. You see, in the circle.ml file, the three coordinates may be seen as x , y , radius So, maybe the pixels are being drawn outside of the visible region of the background, or is too small to view for some reason. Try to tweak around with the dimensions in the circle.ml file to see if this works

I tried that as well, but it did not work. Although it is working in jupyter notebook.
![Screenshot_20231003_133649](https://github.com/Sudha247/ocaml-joy/assets/89303855/7a5f26a3-f87c-40a5-a62f-1484cf8a1c00)

**Comment by nangahamandine** [comment]
> > > > > @Sudha247 and @AryanGodara , I am currently having issues with running OCaml code in vscode, OCaml platform extension has been installed along with the other dependencies but on running this command  "dune exec -- examples/circle.exe" the window displays without the circle. Please, how can I solve this? Here is a snapshot.
> > > > > ![Screenshot_20231003_131752](https://user-images.githubusercontent.com/89303855/272257187-fd5e2482-8894-4ef1-ba29-04851e052f34.png)
> > > > 
> > > > 
> > > > Can you paste the steps you took after cloning the repo and the versions of your opam dependencies (dune graphics base server lap server etc) to get more idea
> > > 
> > > 
> > > After cloning the repo, I created and switched to a new branch, then I navigated to the ocaml-joy directory and ran the following commands:
> > > 
> > > 1. dune build examples/  ( after building the pfoject I then ran the following command)
> > > 2. dune exec -- examples/circle.exe
> > > 
> > > Here are the versions of opam, dune, and graphics: opam version = 2.1.3 dune version =3.10.0 graphics version = 5.1.2
> > > I don't know if this is enough information to help troubleshoot the problem
> > 
> > 
> > @FanyamTerkuma I think I understand your issue. It may be regarding the dimensions of the background and the circle. You see, in the circle.ml file, the three coordinates may be seen as x , y , radius So, maybe the pixels are being drawn outside of the visible region of the background, or is too small to view for some reason. Try to tweak around with the dimensions in the circle.ml file to see if this works
> 
> I tried that as well, but it did not work. Although it is working in jupyter notebook. ![Screenshot_20231003_133649](https://user-images.githubusercontent.com/89303855/272358298-7a5f26a3-f87c-40a5-a62f-1484cf8a1c00.png)

I was going to propose that you tweak the dimensions but I noticed that it's already been proposed. 

I faced a similar issue with another illustration but it displayed when I increased the dimensions to (1000, 1000)

Well, since it is working with Jupyter notebooks, maybe you just test the illustrations with that for now.

**Comment by FanyamTerkuma** [comment]
> > > > > > @Sudha247 and @AryanGodara , I am currently having issues with running OCaml code in vscode, OCaml platform extension has been installed along with the other dependencies but on running this command  "dune exec -- examples/circle.exe" the window displays without the circle. Please, how can I solve this? Here is a snapshot.
> > > > > > ![Screenshot_20231003_131752](https://user-images.githubusercontent.com/89303855/272257187-fd5e2482-8894-4ef1-ba29-04851e052f34.png)
> > > > > 
> > > > > 
> > > > > Can you paste the steps you took after cloning the repo and the versions of your opam dependencies (dune graphics base server lap server etc) to get more idea
> > > > 
> > > > 
> > > > After cloning the repo, I created and switched to a new branch, then I navigated to the ocaml-joy directory and ran the following commands:
> > > > 
> > > > 1. dune build examples/  ( after building the pfoject I then ran the following command)
> > > > 2. dune exec -- examples/circle.exe
> > > > 
> > > > Here are the versions of opam, dune, and graphics: opam version = 2.1.3 dune version =3.10.0 graphics version = 5.1.2
> > > > I don't know if this is enough information to help troubleshoot the problem
> > > 
> > > 
> > > @FanyamTerkuma I think I understand your issue. It may be regarding the dimensions of the background and the circle. You see, in the circle.ml file, the three coordinates may be seen as x , y , radius So, maybe the pixels are being drawn outside of the visible region of the background, or is too small to view for some reason. Try to tweak around with the dimensions in the circle.ml file to see if this works
> > 
> > 
> > I tried that as well, but it did not work. Although it is working in jupyter notebook. ![Screenshot_20231003_133649](https://user-images.githubusercontent.com/89303855/272358298-7a5f26a3-f87c-40a5-a62f-1484cf8a1c00.png)
> 
> I was going to propose that you tweak the dimensions but I noticed that it's already been proposed.
> 
> I faced a similar issue with another illustration but it displayed when I increased the dimensions to (1000, 1000)
> 
> Well, since it is working with Jupyter notebooks, maybe you just test the illustrations with that for now.

Yes, I  guess so.

**Comment by Mankavelda** [comment]
> > > Can you share your opam versions here? You need opam > 2.x.x
> > > Then after setting up correct version of opam, run
> > > ```shell
> > > opam update && opam upgrade
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Then install the required version of dune using
> > > ```shell
> > > opam install "dune=x.y.z" // Keep this `3.0 to 3.9 range`
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > And then you can run the following command inside the examples directory
> > > ```shell
> > > opam install graphics
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This will install the relevant dependencies.
> > > Then run
> > > ```shell
> > > $ cd ocaml-joy // OR cd ..
> > > $ dune build examples/
> > > $ dune exec -- examples/circle.exe
> > > ```
> > 
> > 
> > Hello @AryanGodara, I was able to replicate these steps and my graphics library and dune build are working successfully and I can open run the exec commands for circle and circle graphs. 👍
> 
> That's great @godplayer56 You can now start working on building your own examples from the above list if you have set up the Jupyter kernel

Thank you @AryanGodara

**Comment by Mankavelda** [comment]
I am able to see the circle now
![Screenshot from 2023-10-03 19-42-54](https://github.com/Sudha247/ocaml-joy/assets/95079621/ac9ae24d-e316-482d-8b41-4ff2cdb372ec)

**Comment by nangahamandine** [comment]
> I am able to see the circle now ![Screenshot from 2023-10-03 19-42-54](https://user-images.githubusercontent.com/95079621/272366240-ac9ae24d-e316-482d-8b41-4ff2cdb372ec.png)

Yay!!!

**Comment by Sudha247** [comment]
Thanks for the work everyone! Since we have most of the illustrations in the list in open PRs, I'm closing this issue. Anybody already working on an illustration that's not present in the existing PRs, you can continue to do so. For people starting new, please look at other issues.

**Comment by fiona-max** [comment]
> > @nangahamandine
> > > still no difference.
> > 
> > 
> > Do you mean dune still doesn't recognise that the graphics library is installed? It's quite odd. Anyways, I see that you're on a Windows machine. It's recommended to use WSL for running OCaml. You can perhaps try that.
> > @waringa-mercy - yes, you can go ahead with any of the unclaimed illustrations mentioned in this issue.
> > @joanita-51 - sure, that sounds great!
> 
> Yes. Okay, I'm presently setting up wsl

Please was the wsl helpful? If yes please could you tell me how you did it? I have a Windows computer.

**Comment by nangahamandine** [comment]
> > > @nangahamandine
> > > > still no difference.
> > > 
> > > 
> > > Do you mean dune still doesn't recognise that the graphics library is installed? It's quite odd. Anyways, I see that you're on a Windows machine. It's recommended to use WSL for running OCaml. You can perhaps try that.
> > > @waringa-mercy - yes, you can go ahead with any of the unclaimed illustrations mentioned in this issue.
> > > @joanita-51 - sure, that sounds great!
> > 
> > 
> > Yes. Okay, I'm presently setting up wsl
> 
> Please was the wsl helpful? If yes please could you tell me how you did it? I have a Windows computer.

Hi @fiona-max, I've outline the steps you can follow in the issue you're working on. Please try it out and see. Would be there to hep in whatever way I can
