### ISSUE TITLE
Transformation: rotate

### ISSUE THREAD

**Issue by Sudha247** [Sudha247/ocaml-joy#30]
A `rotate` transformation is a powerful tool for generating illustrations. `rotate d s` returns a shape that's rotation of s by `d` degrees in the cartesian plane. The `graphics` library doesn't have built-in functions for rotations, we might've to do the calculations within joy.

cc/ @FayCarsons who might be interested.

**Comment by Mankavelda** [comment]
Hello @Sudha247 , I am interested in this issue, please can you assign it to me?

**Comment by FayCarsons** [comment]
I had actually asked to be assigned this in #15, so would be happy to :)

**Comment by kushalpokharel** [comment]
I am also interested in this but if it is not available. I would like to be assigned to something like reflection that might come up in the future

**Comment by Sudha247** [comment]
Thanks for the interest and enthusiasm, everyone! Since @FayCarsons expressed interest first, I'll let her pick this up.

@Mankavelda, you can perhaps have a look at #32.

@kushalpokharel, we'll try to create more medium issues soon.

**Comment by nikochiko** [comment]
Merged: https://github.com/Sudha247/ocaml-joy/pull/39
