### ISSUE TITLE
Normalise to a co-ordinate system with (0, 0) at the center

### ISSUE THREAD

**Issue by nikochiko** [Sudha247/ocaml-joy#36]
The canvas provided by `graphics` library starts with `(0, 0)` at the bottom-left corner and all positive co-ordinates. it's easier to draw on a canvas with `(0, 0)` at the center because then the exact dimensions of the canvas don't matter that much.

Transformations such as `translate` already help with this, because shapes start in the center by default and translate can take both positive and negative values for dx and dy. For completeness though, we should also do this by default for new shapes that are created when the optional x and y is provided. 

As part of this task:
* Let the default initialisation use `0, 0` as center rather than `canvas_mid.x` and `canvas_mid.y`
* Take the canvas size into account when actually drawing the shapes (i.e. inside `render_shape`)

**Comment by nangahamandine** [comment]
Hi, can I work on this?

**Comment by nikochiko** [comment]
Sure, go ahead

**Comment by nangahamandine** [comment]
Okay, thanks

**Comment by nangahamandine** [comment]
I want to redo all the changes I made and open another PR in order to effectively implement the necessary changes. My apologies for all the confusion. Please give me time to go through all your corrections again and redo the issue. 
Thank you for being patient with me.

**Comment by nikochiko** [comment]
Merged: https://github.com/Sudha247/ocaml-joy/pull/43
