### ISSUE TITLE
Format the source code

### ISSUE THREAD

**Issue by Sudha247** [Sudha247/ocaml-joy#5]
I just realised that some parts of the code are not linted. Run the source code through ocamlformat. For reference - https://dune.readthedocs.io/en/stable/howto/formatting.html

**Comment by fiona-max** [comment]
Good day, sir can I be assigned this issue?

**Comment by Sudha247** [comment]
Hi @fiona-max, thanks for your interest in contributing. Feel free to go ahead.

**Comment by Sudha247** [comment]
Hi @fiona-max, are you still working on this. Please don't hesitate to post here if you have any questions.

**Comment by fiona-max** [comment]
Good day sir,
I've tried to build the project but this is the error I get what can I do?

![image](https://github.com/Sudha247/ocaml-joy/assets/59697024/9117d704-7585-45ad-800e-6951f35dccbb)

**Comment by fiona-max** [comment]
> Hi @fiona-max, are you still working on this. Please don't hesitate to post here if you have any questions.

Yes sir I'm still working on it.

**Comment by nikochiko** [comment]
@fiona-max please refer to this comment: https://github.com/Sudha247/ocaml-joy/issues/3#issuecomment-1744606554

**Comment by fiona-max** [comment]
> @fiona-max please refer to this comment: [#3 (comment)](https://github.com/Sudha247/ocaml-joy/issues/3#issuecomment-1744606554)

Thank sir. I did update the dune version as instructed in the comment and it is successful but when I check the version using the command dune --version it still displays the version that was previously there.

**Comment by nikochiko** [comment]
Did you run `opam update` and `opam upgrade` both?

**Comment by nikochiko** [comment]
The above command had fixed it for me by upgrading the dune version when I ran into it.

**Comment by fiona-max** [comment]
This is the issue I have at the moment sir
![image](https://github.com/Sudha247/ocaml-joy/assets/59697024/1481c88d-9b5a-4491-babd-553b013a1d91)

**Comment by joanita-51** [comment]
@fiona-max , are you still encountering issues with this? If yes, what are they? I have also followed https://github.com/Sudha247/ocaml-joy/issues/3#issuecomment-1744606554 and I was able to get a circle as my output

**Comment by joanita-51** [comment]
@Sudha247 After following the instructions in the article, I've noticed that there are red underlines on the modified files in my project.
Here's a screenshot for reference:
![image](https://github.com/Sudha247/ocaml-joy/assets/82649346/b373d406-046f-479a-ae06-78fc759568ee)

**Comment by joanita-51** [comment]
> @Sudha247 After following the instructions in the article, I've noticed that there are red underlines on the modified files in my project. Here's a screenshot for reference: ![image](https://user-images.githubusercontent.com/82649346/272687275-b373d406-046f-479a-ae06-78fc759568ee.png)

To resolve these red underlines, I executed the `dune build` command, and they disappeared.

**Comment by nikochiko** [comment]
@joanita-51 does the project compile successfully for you? (i.e. does `dune build` work without errors?)

**Comment by joanita-51** [comment]
> @joanita-51 does the project compile successfully for you? (i.e. does `dune build` work without errors?)

Yes, it does. My question is how can we confirm that the source code has been properly formatted?

**Comment by nikochiko** [comment]
> > @joanita-51 does the project compile successfully for you? (i.e. does `dune build` work without errors?)
> 
> Yes, it does. My question is how can we confirm that the source code has been properly formatted?

A red line in VSCode generally indicates an error. A yellow line is a formatting issue.

As long as the project builds successfully with `dune build`, you can safely ignore the red warnings. What this means is that your VS Code tooling is not set up properly, rather than it being the problem with the source code.

**Comment by joanita-51** [comment]
> > > @joanita-51 does the project compile successfully for you? (i.e. does `dune build` work without errors?)
> > 
> > 
> > Yes, it does. My question is how can we confirm that the source code has been properly formatted?
> 
> A red line in VSCode generally indicates an error. A yellow line is a formatting issue.
> 
> As long as the project builds successfully with `dune build`, you can safely ignore the red warnings. What this means is that your VS Code tooling is not set up properly, rather than it being the problem with the source code.

Great! I can also visually confirm that the modified file's shape has been updated as expected.
![image](https://github.com/Sudha247/ocaml-joy/assets/82649346/c86ac865-f579-4761-b00c-c2d7be508275)

**Comment by joanita-51** [comment]
@nikochiko, would it be a good time to create a PR now?

**Comment by nikochiko** [comment]
@fiona-max is working on this issue at the moment.

@joanita-51 please wait for some time. I'll create another issue for you take up.

**Comment by joanita-51** [comment]
> @fiona-max is working on this issue at the moment.
> 
> @joanita-51 please wait for some time. I'll create another issue for you take up.

Alright

**Comment by nikochiko** [comment]
> This is the issue I have at the moment sir The versions don't match ![image](https://user-images.githubusercontent.com/59697024/272634634-1481c88d-9b5a-4491-babd-553b013a1d91.png)

I think your issue is with multiple `opam switch`es present, and you might be getting the incorrect `dune` because the version looks correct in the output of `opam list`.

Did you follow the opam instructions, e.g. `opam init` and `eval $(opam env)`?

Maybe try this:
1. Run `opam switch list`
2. Try out different switches from the list with `opam switch <switch-name>` (e.g. `opam switch 5.1.0`)
3. Try running `dune build` with each. My hunch is that one of them should work.

**Comment by fiona-max** [comment]
> > This is the issue I have at the moment sir The versions don't match ![image](https://user-images.githubusercontent.com/59697024/272634634-1481c88d-9b5a-4491-babd-553b013a1d91.png)
> 
> I think your issue is with multiple `opam switch`es present, and you might be getting the incorrect `dune` because of that. The version in the output of `opam list` looks correct.
> 
> Did you follow the opam instructions, e.g. `opam init` and `eval $(opam env)`?
> 
> Maybe try this:
> 
> 1. Run `opam switch list`
> 2. Try out different switches from the list with `opam switch <switch-name>` (e.g. `opam switch 5.1.0`)
> 3. Try running `dune build` with each. My hunch is that one of them should work.

Ok, sir. Thank you.
 Let me try it out.

**Comment by fiona-max** [comment]
Hello sir. Please these are the errors I'm facing at the moment. I have dune v 3.6.2, graphics v 5.1.2, ocaml v 4.14.0 and opam 2.2.0~alpha0~20221228. 
1 - 
![image](https://github.com/Sudha247/ocaml-joy/assets/59697024/fda64c1e-0e48-4bed-ad43-0cc754a72f1a)
2 - Here even after modifying the dune lang i still get this error 
![image](https://github.com/Sudha247/ocaml-joy/assets/59697024/ea2d6248-4d56-465a-88ea-4f2dfa7876da)

**Comment by nangahamandine** [comment]
> Hello sir. Please these are the errors I'm facing at the moment. I have dune v 3.6.2, graphics v 5.1.2, ocaml v 4.14.0 and opam 2.2.0~alpha0~20221228. 1 - ![image](https://user-images.githubusercontent.com/59697024/272756699-fda64c1e-0e48-4bed-ad43-0cc754a72f1a.png) 2 - Here even after modifying the dune lang i still get this error ![image](https://user-images.githubusercontent.com/59697024/272757063-ea2d6248-4d56-465a-88ea-4f2dfa7876da.png)
> 
> Please sir what can I do? I read through the comments on the other issues. I've been stuck on this for a while now.

I'm sorry about your errors. I encountered multiple errors as well but I read several resources online, tried several methods and now I'm not sure which finally did it.

Let's start with this. I notice you're on a windows directory that's why you're getting the errors.  You're not actually using the switch atm.
What you need to do is connect your VS Code to WSL first and make sure that you can access the project from there. It could help is you cloned the repo into your WSL directly. Just make sure not to clone it into the root. best if you do it at home/your-directory...
So for now, forget about this cloned repo saved in your windows computer and try to do it in your WSL.

Start with the above then when you're done, open your terminal directly from VS Code and run all the commands you've been running that @nikochiko provided above and see. 

Everything above played a role in me succeeding to run my project. Hope it helps.

**Comment by nangahamandine** [comment]
As indicated on the screenshot below, the arrow at the bottom is what your interface will look like when you connect your VS Code to WSL. 
The arrow above shows what it looks like when you clone your repo in WSL.

![Screenshot](https://github.com/Sudha247/ocaml-joy/assets/78376414/ed2d2d09-e826-4615-abee-90f641e1b153)

**Comment by nangahamandine** [comment]
Hi @fiona-max did you succeed?

**Comment by nangahamandine** [comment]
> > Hi @fiona-max did you succeed?
> 
> I did set up the WSL

Okay, awesome!

**Comment by fiona-max** [comment]
> > > Hi @fiona-max did you succeed?
> > 
> > 
> > I did set up the WSL
> 
> Okay, awesome!

I still have the same error after doing all that you suggested

**Comment by nangahamandine** [comment]
Did you navigate to your projects new directory before trying to build your project? Also, did you do everything proposed by @nikochiko above?

**Comment by nikochiko** [comment]
@nangahamandine thanks for helping @fiona-max with the windows setup! ⭐ 

@fiona-max -- the graphics library is missing from your setup. can you try this after running `opam install graphics`?

**Comment by fiona-max** [comment]
> Did you navigate to your projects new directory before trying to build your project? Also, did you do everything proposed by @nikochiko above?

Yes I did

**Comment by nikochiko** [comment]
> it looks like the graphics library is missing from your setup. can you try this after running opam install graphics?

@fiona-max did you try this?

**Comment by nikochiko** [comment]
@fiona-max I'm un-assigning you from this issue for now. Please take up another good-first-issue once your setup is running.

**Comment by Sudha247** [comment]
Do we have another volunteer while @fiona-max is looking at fixing their setup? This should be a reasonably straightforward change. The process is explained here: https://dune.readthedocs.io/en/stable/howto/formatting.html.

**Comment by joanita-51** [comment]
> Do we have another volunteer while @fiona-max is looking at fixing their setup? This should be a reasonably straightforward change. The process is explained here: https://dune.readthedocs.io/en/stable/howto/formatting.html.

@Sudha247 , I can do that since I have done it before

**Comment by joanita-51** [comment]
@Sudha247 ,  I encounter an error when running `dune build`
![image](https://github.com/Sudha247/ocaml-joy/assets/82649346/dc384ab2-03a5-48d8-8e17-559eb46000d5)

originating from this function.
![image](https://github.com/Sudha247/ocaml-joy/assets/82649346/f6df8bb2-eed7-4529-8ef6-68c88ceb911d)

**Comment by nangahamandine** [comment]
Basically, we need to update the rotate implementation to look like this:

``
let rotate degrees shape = 
  match shape with 
  | Circle circle -> Circle { c = (rot circle.c degrees); radius = circle.radius }
  | Rectangle rectangle -> Rectangle { c = (rot rectangle.c degrees); length = rectangle.length; width = rectangle.width }
  | Ellipse ellipse -> Ellipse { c = (rot ellipse.c degrees); rx = ellipse.rx; ry = ellipse.ry }
  let rotate degrees shape =
  match shape with
  | Circle circle -> Circle { c = (rot circle.c degrees); radius = circle.radius }
  | Rectangle rectangle -> Rectangle { c = (rot rectangle.c degrees); length = rectangle.length; width = rectangle.width }
  | Ellipse ellipse -> Ellipse { c = (rot ellipse.c degrees); rx = ellipse.rx; ry = ellipse.ry }
  | Line line -> Line {a = (rot line.a degrees); b = (rot line.b degrees)}
``

**Comment by joanita-51** [comment]
> Basically, we need to update the rotate implementation to look like this:
> 
> `let rotate degrees shape = match shape with | Circle circle -> Circle { c = (rot circle.c degrees); radius = circle.radius } | Rectangle rectangle -> Rectangle { c = (rot rectangle.c degrees); length = rectangle.length; width = rectangle.width } | Ellipse ellipse -> Ellipse { c = (rot ellipse.c degrees); rx = ellipse.rx; ry = ellipse.ry } let rotate degrees shape = match shape with | Circle circle -> Circle { c = (rot circle.c degrees); radius = circle.radius } | Rectangle rectangle -> Rectangle { c = (rot rectangle.c degrees); length = rectangle.length; width = rectangle.width } | Ellipse ellipse -> Ellipse { c = (rot ellipse.c degrees); rx = ellipse.rx; ry = ellipse.ry } | Line line -> Line {a = (rot line.a degrees); b = (rot line.b degrees)}`

Alright, thank you @nangahamandine
