### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by Sudha247** [Sudha247/ocaml-joy#50]
To prevent build failures like the ones mentioned in #47, a CI will be useful. We can use GitHub actions and [setup-ocaml](https://github.com/ocaml/setup-ocaml) for setting up the CI. Here's an example - https://github.com/ocaml-multicore/domainslib/blob/main/.github/workflows/main.yml.

**Comment by TitilayoAdeyemi** [comment]
Hi @Sudha247 Would be glad to work on this task.

**Comment by Sudha247** [comment]
Sure, please go ahead.

**Comment by TitilayoAdeyemi** [comment]
Thanks @Sudha247 I'd be on it

**Comment by TitilayoAdeyemi** [comment]
Hello @Sudha247 I have created a PR for this. Kindly review, I'd be expecting feedback. Thanks

**Comment by nangahamandine** [comment]
Great job @TitilayoAdeyemi! :)
Thank you so much for your amazing contribution. Through this, I got to learn more about continuous integration.

I've done a little refactore of the CI in my present PRs so all the checks are passed now with no issues.

**Comment by Sudha247** [comment]
@nangahamandine I noticed the CI failures due to dependencies on windows, too. Can you submit a separate PR for fixing it so we can review and merge it quickly, please?

**Comment by nangahamandine** [comment]
> @nangahamandine I noticed the CI failures due to dependencies on windows, too. Can you submit a separate PR for fixing it so we can review and merge it quickly, please?

Okay, sure. I'll do that now.

**Comment by nangahamandine** [comment]
I've opened a PR for the refactor at PR #70 
Please review.

**Comment by Sudha247** [comment]
Fixed by #97.
