### ISSUE TITLE
Scale transformation corrections

### ISSUE THREAD

**Issue by nikochiko** [Sudha247/ocaml-joy#58]
I realised there are a couple of things wrong with the way we scale:
* we scale linear dimensions by the `sqrt` of the scaling factor. i had suggested this, but it might be more intuitive to scale linearly by that factor. that is also what SVG does, and i feel we should maintain compatibility with SVG as much as possible for supporting multiple backends
* we scale while keeping the center point same. this will break when we are scaling groups of shapes (one example was discussed by taking the line as an example here -- https://github.com/Sudha247/ocaml-joy/issues/49#issuecomment-1765940845). (e.g. three non-intersecting shapes will start intersecting when we scale them all as a complex shape).

e.g. we should be getting the scaled shapes like in the bottom canvas
<img width="573" alt="image" src="https://github.com/Sudha247/ocaml-joy/assets/37668193/62052cc4-eeb9-4f40-bb24-f3893b23b04e">

The new calculations should handle the shapes like:
* [ ] #61
* [ ] #62
* [ ] polygons -> multiply x and y coordinates of all points by the scaling factor (new shape type, to be added) -- #59

**Comment by nikochiko** [comment]
This can be broken down into a couple of issues

**Comment by FayCarsons** [comment]
I can take this one on!

**Comment by nikochiko** [comment]
@FayCarsons I've broken this down to three separate issues. Would you like to take up https://github.com/Sudha247/ocaml-joy/issues/59 ?

**Comment by FayCarsons** [comment]
Sure, but I'd also be happy to take on all of them if that'd be helpful!
