### ISSUE TITLE
radius -> multiply linearly by scaling factor

### ISSUE THREAD

**Issue by nikochiko** [Sudha247/ocaml-joy#62]
In the `scale` transformation that we have, I had initially suggested that we `scale` the *area* by the scaling factor, but that's not as intuitive and also not compatible with SVGs.

We should instead scale linearly by the scaling factor as compared to scaling by its square root.

**Comment by TitilayoAdeyemi** [comment]
Hello @nikochiko I'd start working on this

**Comment by nikochiko** [comment]
@TitilayoAdeyemi let's work on merging https://github.com/Sudha247/ocaml-joy/pull/41 first

**Comment by TitilayoAdeyemi** [comment]
Hello @nikochiko I have fixed the error in #41, I would like you to review it for me while I start working on this one. Thank you

**Comment by TitilayoAdeyemi** [comment]
Hello @nikochiko @Sudha247 
I created a PR for this, also, I worked on #61 as well. Would really love for you to review the code. Thank you!
