### ISSUE TITLE
Add test for rectangle

### ISSUE THREAD

**Issue by Sudha247** [Sudha247/ocaml-joy#8]
Similar to the [circle test](https://github.com/Sudha247/ocaml-joy/blob/main/test/test_circle.ml), add a test to validate that `Joy.Shape.rectangle` indeed produces correct output. The test file needs to go into the `test` directory.

**Comment by godplayer56** [comment]
@Sudha247 Since I have already opened the PR for this, can you assign me this issue?

**Comment by nangahamandine** [comment]
Hello
Since no one  is assigned to this, can I work on it? I've opened a PR with illustrations from all the geometric shapes that were mentioned in #3 with 2 others, including the triangle. I could proceed to write tests for the rectangle and all the other shapes if that's okay.

**Comment by Sudha247** [comment]
@godplayer56, yes you can go ahead with rectangle.

@nangahamandine, will get to reviewing your illustrations in a bit. Meanwhile, you can take a look at #12.

**Comment by nangahamandine** [comment]
> @godplayer56, yes you can go ahead with rectangle.
> 
> @nangahamandine, will get to reviewing your illustrations in a bit. Meanwhile, you can take a look at #12.

Okay, thank you

**Comment by godplayer56** [comment]
Hey @Sudha247 , I was working on the test file and there are some doubts which I can't figure out - 
I ran dune test and dune runtest and both are not working, maybe because the test_circle file is incomplete or there is some error with my system which I am not able to figure out.

I wasn't able to figure out about how exactly should I structure the test file. In dune documentation which I read it says that there are inline_tests or custom test which can be written. Can you tell me which one of these should I use?

Moreover whenever I try to use `ppx_inline_tests` in the dune file it shows that the current version of opam that I switched to was not supporting this package. How should I go about solving these issues?

**Comment by Sudha247** [comment]
@godplayer56 which version of opam are you using?

**Comment by nikochiko** [comment]
Documented the issue here -- https://github.com/Sudha247/ocaml-joy/issues/3#issuecomment-1745527468

**Comment by godplayer56** [comment]
> @godplayer56 which version of opam are you using?

Hii @Sudha247 here are the specifications of opam that I am using -
```bash
❯ opam --version                                                             ─╯
2.1.2

```
and here are the version of packages used by opam -
```bash
❯ opam list                                                                  ─╯
# Packages matching: installed
# Name              # Installed # Synopsis
base-bigarray       base
base-bytes          base        Bytes library distributed with the OCaml compile
base-threads        base
base-unix           base
base64              3.5.1       Base64 encoding for OCaml
conf-gmp            4           Virtual package relying on a GMP lib system inst
conf-gmp-powm-sec   3           Virtual package relying on a GMP lib with consta
conf-pkg-config     3           Check if pkg-config is installed and create an o
conf-zlib           1           Virtual package relying on zlib
conf-zmq            0.1         Virtual package relying on zmq library installat
cppo                1.6.9       Code preprocessor like cpp for OCaml
cryptokit           1.18        A library of cryptographic primitives
csexp               1.5.2       Parsing and printing of S-expressions in Canonic
dune                3.11.0      Fast, portable, and opinionated build system
dune-configurator   3.11.0      Helper library for gathering system configuratio
jupyter             2.7.7       An OCaml kernel for Jupyter notebook
logs                0.7.0       Logging infrastructure for OCaml
lwt                 5.7.0       Promises and event-driven I/O
lwt_ppx             2.1.0       PPX syntax for Lwt, providing something similar 
ocaml               4.08.0      The OCaml compiler (virtual package)
ocaml-base-compiler 4.08.0      Official release 4.08.0
ocaml-compiler-libs v0.12.4     OCaml compiler libraries repackaged
ocaml-config        1           OCaml Switch Configuration
ocamlbuild          0.14.2      OCamlbuild is a build system with builtin rules 
ocamlfind           1.9.6       A library manager for OCaml
ocplib-endian       1.2         Optimised functions to read and write int16/32/6
ppx_derivers        1.2.1       Shared [@@deriving] plugin registry
ppx_deriving        5.2.1       Type-driven code generation for OCaml
ppx_deriving_yojson 3.7.0       JSON codec generator for OCaml
ppxlib              0.30.0      Standard infrastructure for ppx rewriters
result              1.5         Compatibility Result module
seq                 base        Compatibility package for OCaml's standard itera
sexplib0            v0.16.0     Library containing the definition of S-expressio
stdint              0.7.2       Signed and unsigned integer types having specifi
stdlib-shims        0.3.0       Backport some of the new stdlib features to olde
topkg               1.0.7       The transitory OCaml software packager
uuidm               0.9.8       Universally unique identifiers (UUIDs) for OCaml
yojson              2.1.0       Yojson is an optimized parsing and printing libr
zarith              1.13        Implements arithmetic and logical operations ove
zmq                 5.2.1       OCaml bindings for ZeroMQ 4.x
zmq-lwt             5.2.1       Lwt-aware bindings to ZMQ

```

**Comment by godplayer56** [comment]
Hey @nikochiko I am having the same issue as described in #27 . I am stuck here for multiple days :sweat:

**Comment by nikochiko** [comment]
Hey @godplayer56 I've fixed this.

Please pull the new changes.

Check out `test/test_all.ml` and `test/test_circle.ml` for an example of tests. We want the tests to show some result and we'll check it manually, one by one, by running `dune exec -- test/test_all.exe`

**Comment by nikochiko** [comment]
@godplayer56 are you still working on this?

**Comment by godplayer56** [comment]
> @godplayer56 are you still working on this?

Yes @nikochiko I have been caught up somewhere else 😅. I'll open a pr for it today 👍

**Comment by nikochiko** [comment]
Merged: https://github.com/Sudha247/ocaml-joy/pull/44
