### ISSUE TITLE
`render` vs `show`

### ISSUE THREAD

**Issue by nikochiko** [Sudha247/ocaml-joy#85]
There should be only one method to render the shapes.

Currently, there are two. Some examples make use of `render` and others use `show`.

Both do the same thing. We should only keep one.

**Comment by FayCarsons** [comment]
I think getting rid of `render` in favor of `show` is probably the best solution. I think passing a singleton list in the case of single-shape sketches shouldn't be too confusing or complicated for beginners or children learning to code.
