### ISSUE TITLE
bug: Drawing circle on a rectangular canvas draws an ellipse

### ISSUE THREAD

**Issue by nikochiko** [Sudha247/ocaml-joy#86]
Code:
```
open Joy

let () =
  init ~size:(500., 300.) ();
  background (1., 1., 1., 1.);
  let c = circle 50. in
  set_color (0., 0., 0.);
  render c;
  write ~filename:"circle.png" ()
```

<img width="608" alt="image" src="https://github.com/Sudha247/ocaml-joy/assets/37668193/df677d4f-69a8-4b99-b288-1f16713de5e9">

The initial cairo scaling must be done by `Cairo.scale (max w h) (max w h)` instead of `Cairo.scale w h`.

**Comment by FayCarsons** [comment]
I tried `max w h` as the args and it caused distortions in the placement of shapes (i.e. a circle at 0,0 was not centered on the Y axis). I think the euclidean norm may work, I'll also test out a few of the aspect ratio correction equations I know. 

Its very odd that it is doing this though, we aren't drawing on a pixel level and this shouldn't really be happening. Or at least, this doesn't happen with frameworks like p5.js or the others I've used. There may be something else at play, some config missing.
