### ISSUE TITLE
Add test for ellipse

### ISSUE THREAD

**Issue by Sudha247** [Sudha247/ocaml-joy#9]
Similar to the [circle test](https://github.com/Sudha247/ocaml-joy/blob/main/test/test_circle.ml), add a test to validate that `Joy.Shape.ellipse` indeed produces correct output. The test file needs to go into the test directory.

**Comment by Mankavelda** [comment]
Hello @Sudha247 I would love to work on this issue

**Comment by Sudha247** [comment]
Sure @Mankavelda, please go ahead.

**Comment by Mankavelda** [comment]
Hello @Sudha247 , please can you help me with this issue? I am facing an error here trying to run the test.
![Screenshot from 2023-10-04 17-42-52](https://github.com/Sudha247/ocaml-joy/assets/95079621/148e5de0-7ecf-4876-8748-cd9ac7ccdb30)

Also, what is Joy? is it a package? I don't seem to understand

**Comment by Mankavelda** [comment]
Also @Sudha247 I did quite get the task. Do you mean I should add test for circle_graph or I should draw an ellipse and add a test for it?

**Comment by nikochiko** [comment]
@Mankavelda 
> Hello @Sudha247 , please can you help me with this issue? I am facing an error here trying to run the test.

Hey, this is fixed.

> Do you mean I should add test for circle_graph or I should draw an ellipse and add a test for it?

You need to use the ellipse from [shape.ml](https://github.com/Sudha247/ocaml-joy/blob/c24273e548175e65c6185fcee1fcfd41a5d8eec8/lib/shape.ml#L45) in a new test file (e.g. `test/test_ellipse.ml` similar to the [circle test](https://github.com/Sudha247/ocaml-joy/blob/main/test/test_circle.ml)). You can add that in [`test/test_all.ml`](https://github.com/Sudha247/ocaml-joy/blob/main/test/test_all.ml).

When you run `dune exec -- test/test_all.exe`, you should see all the tested shapes one by one if you keep pressing enter in the terminal.

**Comment by nikochiko** [comment]
Merged with #16
